### ISSUE TITLE
Can only convert square JuicyPixels images to OpenCV

### ISSUE THREAD

**Issue by ocharles** [LumiGuide/haskell-opencv#111]
Find this little beaut of a bug in the JuicyPixels -> OpenCV code:

```haskell
forM_ ((,) <$> [0 .. h - 1] <*> [0 .. w - 1]) $ \(x,y) ->
```

Can you spot it?

How about if I rewrite the list building:

```haskell
do x <- [0 .. h - 1]
   y <- [0 .. w - 1])
   return (x, y)
```

Whoops! We've accidentally transposed `x` and `y`! The correct loop should be:

```haskell
forM_ ((,) <$> [0 .. h - 1] <*> [0 .. w - 1]) $ \(y,x) ->
```

**Comment by roelvandijk** [comment]
Well spotted! I completely agree with the much more readable version you propose.

Btw, the entire JuicyPixels encoding <-> decoding is extremely slow. It needs a complete rewrite.

**Comment by ocharles** [comment]
It's actually good enough for what I'm doing, so no need to worry about that. Just needs to avoid blowing up with an out of bounds exception :smile:
