### ISSUE TITLE
Build failure: libopencv_stitching.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by basvandijk** [LumiGuide/haskell-opencv#115]
With the recent nixpkgs upgrade to `release-18.03` we get the following error when building `doc-images-opencv` in a `nix-shell`:

```
$ cd opencv
$ nix-shell
$ cabal clean
$ cabal configure --enable-tests
$ cabal build
...
[3 of 3] Compiling Main 
  ( doc/images.hs, dist/build/doc-images-opencv/doc-images-opencv-tmp/Main.o )

<no location info>: error:
    <command line>: can't load .so/.DLL for: 
      libopencv_stitching.so (libopencv_stitching.so: 
        cannot open shared object file: No such file or directory)
```

This happens both on GHC-8.2.2 and GHC-8.4.1.

Note that the package builds successfully with `nix-build` indicating this has something to do with the nix-shell environment. 

Note that `libopencv_stitching.so` exists:

```
$ nix-build -A opencv3
...

$ cat result/lib/pkgconfig/opencv.pc | grep opencv_stitching
Libs: -L${exec_prefix}//nix/store/drh6kwyd88vwh0j1fmnmnsva11by1v6g-opencv-3.4.1/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_modern -lopencv_dnn_objdetect -lopencv_dpm -lopencv_face -lopencv_photo -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_sfm -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core

$ ls -l result/lib/libopencv_stitching.so
lrwxrwxrwx 1 root root 26 Jan  1  1970 result/lib/libopencv_stitching.so -> libopencv_stitching.so.3.4

$ ls -l result/lib/libopencv_stitching.so.3.4
lrwxrwxrwx 1 root root 28 Jan  1  1970 result/lib/libopencv_stitching.so.3.4 -> libopencv_stitching.so.3.4.1

$ ls -l result/lib/libopencv_stitching.so.3.4.1
-r-xr-xr-x 1 root root 632K Jan  1  1970 result/lib/libopencv_stitching.so.3.4.1
```

Note that `-lopencv_stitching` is the first library in the `opencv.pc` file. So it's likely the error has nothing to do with `opencv_stitching` and that something else is going wrong.

**Comment by basvandijk** [comment]
@peti @ocharles have you seen the behavior before that a Haskell package builds using `nix-build` but fails when build using cabal in a `nix-shell`?

**Comment by ocharles** [comment]
I don't believe I have. Sorry :(

**Comment by basvandijk** [comment]
This is fixed when https://github.com/NixOS/nixpkgs/pull/40286 is merged.

**Comment by basvandijk** [comment]
This is now fixed.

**Comment by schell** [comment]
I see this when building with stack using `build.sh`. What happened to be the issue?

**Comment by roelvandijk** [comment]
Well, it was fixed by https://github.com/NixOS/nixpkgs/pull/40286. So it was fixed by changing the package config file for the opencv c++ library.

Are you building with stack using nix integration? Or did you install the opencv c++ library some other way?

**Comment by basvandijk** [comment]
Well Schell is using `build.sh` which builds the OpenCV C++ library using [`travis-build-opencv`](https://github.com/LumiGuide/haskell-opencv/blob/master/travis-build-opencv). This installs the package by invoking `cmake` and `make`. So it looks like there's a bug in creating the `opencv.pc` file that I fix in https://github.com/NixOS/nixpkgs/commit/9938bb6c8259a6772e937b0f01318bc816f67ebe. I was assuming that the faulty `opencv.pc` only happened when building in nixpkgs but now it appears it happens in other situations as well. The best thing would be to report this upstream.

**Comment by basvandijk** [comment]
BTW it's probably a good idea to update the `travis-build-opencv` to install OpenCV-3.4.3 because it now installs 3.4.0. Maybe that fixes things...
