### ISSUE TITLE
Function requires shape at compile time?

### ISSUE THREAD

**Issue by dukedave** [LumiGuide/haskell-opencv#130]
Given this type signature:

https://github.com/LumiGuide/haskell-opencv/blob/1e7f0b49b811bc845250f01a3d24d5ca007a1f76/opencv/src/OpenCV/ImgProc/Drawing.hsc#L686-L691

Specifically `'S [height, width])`:

Does this mean `putText` requires that the shape of the `Mat` be known at compile time?

e.g. if I load in an image:

```hs
  frog :: Mat D ('S 3) ('S Word8)
  frog =
      exceptError $ coerceMat $ unsafePerformIO $
        imdecode ImreadUnchanged <$> B.readFile "kikker.jpg"
```

How can I use `putText`?

I have some rather messy sample code [here](https://github.com/dukedave/pitchskell/blob/91dfcf78a3641b06d8e360f2c6b373ce448a2ade/test/Mat.hs).

**Comment by dukedave** [comment]
I [figured it out](https://github.com/dukedave/pitchskell/blob/master/src/StartFiducialDebug.hs#L25).
Not sure if it's the 'right' way, but it works...

**Comment by basvandijk** [comment]
That's the right way to do it.

The drawing functions take a `Mut (Mat ('S [height, width]) channels depth) (PrimState m)`. This means that it should be statically known that the Mat is 2-dimensional, i.e. `'S [height, width]`. However the drawing functions don't care about the specific dimensions. That's is why the `height` and `width` are fully polymorphic and can thus range over `D` or `S someDimension`.

If you have a Mat with the shape `D` the system doesn't statically know that the Mat is 2-dimensional. So you first need to proof that by coercing the Mat to a Mat with a 2-dimensional shape. This coercing will fail if the Mat has different dimensions.
