### ISSUE TITLE
Offer to help maintain

### ISSUE THREAD

**Issue by ocharles** [LumiGuide/haskell-opencv#156]
Hi all,

It looks like development has slowed here. We're still very heavy users of this library at CircuitHub, and have quite a few of our own fixes. I'd like to offer help maintain this library.

**Comment by roelvandijk** [comment]
Hi Ollie, your help is very welcome! Feel free to merge changes at your leisure. I bumped your repository access level to maintainer.

**Comment by ocharles** [comment]
Ah wonderful, thanks!
