### ISSUE TITLE
Expose OpenCV.C

### ISSUE THREAD

**Issue by chpatrick** [LumiGuide/haskell-opencv#23]
Hi, could you expose the OpenCV.C modules so that external users can interface with native OpenCV code?

**Comment by roelvandijk** [comment]
We can certainly do that. But we should first rename them to make it explicit that they are internal modules. Something like `OpenCV.Internal.C`. With the same change I would also want to expose all internal modules.

Every internal module must come with an appropriate warning in the documentation. I'm thinking of using the same wording as in [opaleye's readme](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/README.md).

**Comment by roelvandijk** [comment]
Implemented in b9dde6f61e6efbb9496165748c458f5ee16657de
