### ISSUE TITLE
Fix build in travis

### ISSUE THREAD

**Issue by basvandijk** [LumiGuide/haskell-opencv#29]
On Aug 25 the travis build started [failing](https://travis-ci.org/LumiGuide/haskell-opencv/jobs/155060890#L935) because of:

```
$ ./travis-build-opencv
...
make[2]: *** No rule to make target `/usr/lib/libjpeg.so', needed by `lib/libopencv_imgcodecs.so.3.1.0'.  Stop.
```

@bitonic any idea how to fix this?

**Comment by bitonic** [comment]
@basvandijk not off the top of my head, I'll take a look
