### ISSUE TITLE
`ArraysOfArrays` and `std::vector<Mat>`

### ISSUE THREAD

**Issue by tolysz** [LumiGuide/haskell-opencv#42]
I would like to implement some more of [Computational Photography](http://docs.opencv.org/3.1.0/d1/d79/group__photo__denoise.html)
But as a starter, they need to have some more complicated inputs eg. as `std::vector<Mat>`

So I guess if we could have `[Mat]` converted into `std::vector<Mat>` any ideas how to do it?

I will try the same way as : [matMerge](http://lumiguide.github.io/haskell-opencv/doc/src/OpenCV-Core-ArrayOps.html#matMerge)

**Comment by basvandijk** [comment]
[withArrayPtr](https://github.com/LumiGuide/haskell-opencv/blob/3bae302fa672139fd54e6fbbc7de4da95c3f4f24/src/OpenCV/Internal/Core/Types.hs#L222) is probably the function you need.

I'm looking forward to you pull requests!

**Comment by tolysz** [comment]
So the current version "best" way will is to initialise [`std::vector` from array ](https://github.com/LumiGuide/haskell-opencv/pull/43/files/b7d1406bda65f460d7ddc060a2c693e9b44e7960#diff-d7220dc933e817b787cb534d5c867448R229)
I still think there could be less copying, but it can do for now,

**Comment by basvandijk** [comment]
It would be great if we had a way with less copying.

BTW I might be missing something but shouldn't the buffer be initialised using:

```c++
std::vector<Mat> buffer( $(Mat * srcVecPtr), $(Mat * srcVecPtr) + $(int32_t c'temporalWindowSize) * sizeof(Mat));
```

instead of your [current](https://github.com/LumiGuide/haskell-opencv/blob/master/src/OpenCV/Photo.hs#L227):

```c++
std::vector<Mat> buffer( $(Mat * srcVecPtr), $(Mat * srcVecPtr) + $(int32_t c'temporalWindowSize) );
```

**Comment by basvandijk** [comment]
Please ignore my previous comment. Adding to a pointer already takes the pointer type into account. I shouldn't review code late in the evening after having consumed alcohol on  a holiday in Spain...

**Comment by basvandijk** [comment]
There's nothing left to do here right?
