### ISSUE TITLE
Illegal equational constraint

### ISSUE THREAD

**Issue by Chuck-Aguilar** [LumiGuide/haskell-opencv#46]
Hi! 
I'm trying to use the _blur_, but I can't I get this error. 
`Illegal equational constraint CV.Elem
                                        depth
                                        '[GHC.Word.Word8, GHC.Word.Word16, GHC.Int.Int16, Float, Double]
                                      ~ 'True
        (Use GADTs or TypeFamilies to permit this)
        When checking that ‘blurImage’ has the inferred type
          blurImage :: forall (m :: * -> *)
                              (shape :: CV.DS [CV.DS GHC.TypeLits.Nat])
                              (channels :: GHC.TypeLits.Nat)
                              depth.
                       (Applicative m,
                        CV.Elem
                          depth
                          '[GHC.Word.Word8, GHC.Word.Word16, GHC.Int.Int16, Float, Double]
                        ~ 'True) =>
                       M.Mat shape ('CV.S channels) ('CV.S depth)
                       -> CV.CvExceptT m (M.Mat shape ('CV.S channels) ('CV.S depth))
`
But I'm using something like the example here: [blur](http://lumiguide.github.io/haskell-opencv/doc/OpenCV-ImgProc-ImgFiltering.html#v:blur)

`blurImage image = CV.pureExcept $ CV.blur (V2 13 13 :: V2 Int32) image`

And I call it from here: 

`blurred  <- blurImage (getImageFromEither resized)`

Where `getImageFromEither` returns a `M.Mat shape ('CV.S channels) ('CV.S depth)`, it means, it returns a normal image. 

Does anybody know what's wrong?

Thank you!

**Comment by roelvandijk** [comment]
You probably need to enable the `TypeFamilies` language extension. This is hinted at by GHC: 

> Use GADTs or TypeFamilies to permit this

The executable `opencv-doc-images` which executes the _blur_ example has the following language extensions enabled:

```
    default-extensions:
        BangPatterns
        DataKinds
        LambdaCase
        OverloadedStrings
        PackageImports
        PolyKinds
        ScopedTypeVariables
        TupleSections
        TypeFamilies
        TypeOperators
```

We should probably add some documentation about the environment in which all the examples are compiled and executed.

**Comment by Chuck-Aguilar** [comment]
Beautiful. Thank you! I just need to add "{-# LANGUAGE TypeFamilies #-}" in the .hs Thank you!
