### ISSUE TITLE
Troubles with gaussianBlurImage

### ISSUE THREAD

**Issue by Chuck-Aguilar** [LumiGuide/haskell-opencv#51]
Hi!
I was trying to use gaussianBlurImage, but there's an error that I can't recognize. 

I have this: (of course, indented) 
`cropped image = do` 
    `resized               <- resizeImage image`
    `gaussianBlurred <- gaussianBlurImage ((M.unsafeCoerceMat . getImageFromEither) resized)`
Where **resized** is a _Either CV.Exception (M.Mat shape channels depth)_ And I get just: _ Mat shape (S channels) (S depth)_ as `gaussianBlur` function need. 

The I defined `gaussianBlurImage` so:

`gaussianBlurImage image = runExceptT $ CV.pureExcept $ CV.gaussianBlur (V2 13 13 :: V2 Int32) 0 0 image`

And for me, it looks fine. But I get this error:
 `Couldn't match expected type ‘'True’
                    with actual type ‘Elem depth0 '[Word8, Word16, Float, Double]’`

And I don't know either what's happening  or how to solve it. 
Thank you for your help!

**Comment by Chuck-Aguilar** [comment]
I noticed right now, that my `gaussianBlurImage` has this type: 

`gaussianBlurImage :: (M.Mat shape0 ('S channels0) ('S depth0)) -> Either CV.CvException (Either CV.CvException (M.Mat shape0 ('S channels0) ('S depth0)))` 

And I liked this one:

`gaussianBlurImage :: (M.Mat shape0 ('S channels0) ('S depth0)) -> Either CV.CvException (M.Mat shape0 ('S channels0) ('S depth0))`

Maybe it has something to do.

**Comment by Chuck-Aguilar** [comment]
I tried it with medianBlur, blur and with gaussianBlur. I used a not resized image,  and image with three channels and another with 2 (color and gray), and I always get the same error. I'm wondering if the error is in `M.unsafeCoerceMat image`. And why _'True_ as expected type? I don't have idea :smile:

**Comment by Chuck-Aguilar** [comment]
I already found the problem :sweat_smile: 
_Couldn't match expected type ‘'True’ with actual type ‘Elem depth0 '[Word8, Word16, Float, Double]’_

It's due, 'cause `Elem depth0 '[Word8, Word16, Float, Double]` should return `True` or `False`, but I don't know why it doesn't return either True or False, but `Elem depth0 '[Word8, Word16, Float]` I saw, that I've `import OpenCV.TypeLevel` where is `Elem` [Elem](http://lumiguide.github.io/haskell-opencv/doc/OpenCV-TypeLevel.html#t:Elem), so I don't know why it doesn't work ... 

Sorry that I'm speaking so much :sweat_smile: I'm student and I'm trying to write my project on Haskell and not on Python :sweat_smile:

**Comment by roelvandijk** [comment]
It looks like your `depth0` type doesn't satisfy the constraint that it should be one of `Word8`, `Word16`, `Float` or `Double`. For this function the depth must be statically known, so it can not be completely polymorphic.

It would also be helpful if you could post a complete example. Maybe as a github gist or something like that.

**Comment by Chuck-Aguilar** [comment]
Thank you! :) 

Here's the Gist 

https://gist.github.com/Chuck-Aguilar/2a4a0506c2924c4d72134a45dc19935c

**Comment by roelvandijk** [comment]
```haskell
medianBlurImage :: (M.Mat shape0 ('S channels0) ('S depth0)) -> CV.CvExcept (M.Mat shape0 ('S channels0) ('S depth0)) 
medianBlurImage image = CV.medianBlur image 13 --Trying to do it "pure", but telling the Type.
```

If you look at the type of [CV.medianBlur](http://lumiguide.github.io/haskell-opencv/doc/OpenCV-ImgProc-ImgFiltering.html#v:medianBlur) you will see that there are constraints on both the `depth` and `channels` type parameters. In your type annotation you do not mention those constraints. 

A simple fix is directly copying the constraint 
```haskell 
(depth `In` '[Word8, Word16, Float], channels `In` '[1, 3, 4])
````
and adding it to your type. Which should give you:

```haskell
medianBlurImage 
    :: (depth `In` '[Word8, Word16, Float], channels `In` '[1, 3, 4]) 
    => (M.Mat shape ('S channels) ('S depth)) 
    -> CV.CvExcept (M.Mat shape ('S channels) ('S depth)) 
medianBlurImage image = CV.medianBlur image 13
```

Is this helpful?

**Comment by Chuck-Aguilar** [comment]
Thank you for your answer. 
I updated the gist. 
But now I get this error ` Couldn't match type ‘IO’ with ‘Either CV.CvException’
        Expected type: Either CV.CvException ()
          Actual type: IO ()` And that's pretty weird, 'cause I should be able to show the image. When I used `resize` it worked. But with medianBlur (or with another blur) it doesn't work .

**Comment by roelvandijk** [comment]
I don't know at what line you are getting that error. But I do find something a bit strange about your `blurImage` function.

The `blur` function from this library returns a result wrapped in `CvExcept a`. Which is just a type synonym for `Except CvException a`. You can convert this to `Either CvException a` using the `runExcept` function from the `transformers` package.

You are complicating things a bit by first converting `Except CvException a` to `ExceptT CvException IO a` (via `pureExcept`) and then running the entire thing with `runExceptT`. That should result in the type `IO (Either CvException a)`. Which is probably not what you intended.

**Comment by Chuck-Aguilar** [comment]
I see. But I mean, I don't use right now the `blurImage` function. I was just testing with it. The function that I'm using is `medianBlurImage`. 

You can see the [gist](https://gist.github.com/Chuck-Aguilar/2a4a0506c2924c4d72134a45dc19935c) now. I "purify" it. 

Now the problem is much easy to see.

As you can see, in Lib.hs I have **three** ways to define `controller`. 
If I use the **first** or the **second** one, I get this error in the line 22:9: `Couldn't match type ‘()’ with ‘CV.Mat ('CV.S '[height0, width0]) ('CV.S channels) ('CV.S depth)’ Expected type: IO (IO (CV.Mat ('CV.S '[height0, width0]) ('CV.S channels) ('CV.S depth))) Actual type: IO (IO ())`
If I use the **third** one, I get this error in the line 22:9: `Couldn't match expected type ‘'True’ with actual type ‘CV.Elem depth0 '[Word8, Word16, Float]’`

And I can understand both errors, but I don't know how to solve it. I was trying a lot and there's no way for me. What I want to do should be quite simple. I want to get an image, make a _medianBlur_ and show the image.

Many thanks for your help!

**Comment by basvandijk** [comment]
Note that the type of `cropImage` is: 

```haskell
cropImage 
    :: forall height0, width0, channels, depth
     . ( depth `In` '[Word8, Word16, Float]
       , channels `In` '[1, 3, 4]
       ) 
    => M.Mat ('S '[height0, width0]) ('S channels) ('S depth) 
    -> IO ()
```

So it accepts the image `M.Mat ('S '[height0, width0]) ('S channels) ('S depth)` *forall* `height0`, `width0`, `channels` and `depth`! 

The problem is that in `cropImage (M.unsafeCoerceMat img)` the value resulting from  `M.unsafeCoerceMat img` is ambiguous since you haven't specified which specific `height0`, `width0`, `channels` and `depth` you want it to have.

The solution is to tell GHC what you want by giving a type signature to `M.unsafeCoerceMat img` like for example:

```haskell
cropImage (M.unsafeCoerceMat img :: M.Mat ('S '[ 'D, 'D]) ('S 3) ('S Word8))
```

Of course you do need to make sure that `img` has those particular properties!

Good luck!

**Comment by Chuck-Aguilar** [comment]
Hey, thanks! Now everything works. :) I resize the Image, and then I blur it and show it. So, quite nice. Thank you!
