### ISSUE TITLE
Build fails on NixOS-16.09: GHC-8.0.1: Loading temp shared object failed 

### ISSUE THREAD

**Issue by basvandijk** [LumiGuide/haskell-opencv#65]
On the current NixOS-16.09 building haskell-opencv fails with the following error:

```
...
[36 of 69] Compiling OpenCV.Internal.Core.Types.Mat ( src/OpenCV/Internal/Core/Types/Mat.hs, dist/build/OpenCV/Internal/Core/Types/Mat.o )

<no location info>: error:
    ghc: panic! (the 'impossible' happened)
  (GHC version 8.0.1 for x86_64-unknown-linux):
	Loading temp shared object failed: /run/user/1001/ghc15327_0/libghc_273.so: undefined symbol: inline_c_OpenCV_Internal_Exception_1_2402dbf3aea4f7f79392b71ed42618962a22e9aa
```

See https://github.com/NixOS/nixpkgs/issues/18558 for more details.

**Comment by afwlehmann** [comment]
Hm, looks similar to what happens to me everytime when I want to start up `stack ghci`:

```
ghc: panic! (the 'impossible' happened)
  (GHC version 8.0.1 for x86_64-unknown-linux):
	Loading temp shared object failed: /tmp/ghc18542_0/libghc_1.so: undefined symbol: _ZTVN2cv9ExceptionE
```

... the difference being of course that the missing symbol is clearly related to some inlined or wrapped OpenCV type whereas it is totally unclear in the second case.

**Comment by basvandijk** [comment]
I [fixed](https://github.com/LumiGuide/haskell-opencv/commit/5ea490af7662fe74b3740619963d37f1fd91e3d4) it by disabling the `bindnow` hardening feature.

@afwlehmann disabling `bindnow` will probably also solve your `stack ghci` problem.

Maybe the right approach would be to disable `bindnow` for all haskell packages. I will ask @peti what he thinks about that in the upstream issue.

**Comment by nh2** [comment]
I'm having this problem too with my package depending on `haskell-opencv`.

@basvandijk Where would I have to stick the `hardeningDisable` settings if my `shell.nix` looked like the minimal stack-based nix example, e.g. 

```
{ nixpkgs ? import <nixpkgs> {}, ghc }:

with nixpkgs;

haskell.lib.buildStackProject {
  name = "myproject";
  buildInputs =
    [ 
      opencv3
    ];
  inherit ghc;
}
```

Where would it have to go in this case?

**Comment by nh2** [comment]
> Where would it have to go in this case?

Ah, I think I figured:

```
{ nixpkgs ? import <nixpkgs> {}, ghc }:

with nixpkgs;

haskell.lib.buildStackProject {
  name = "myproject";
  buildInputs =
    [ 
      opencv3
    ];
  inherit ghc;

  hardeningDisable = [ "bindnow" ];
  shellHook = ''
    export hardeningDisable=bindnow
  '';
}
```

Simply at the end. I think I tried it the first time and it didn't work; might have been that I had to `stack clean` for it to work?

**Comment by basvandijk** [comment]
@nh2 TIL about the existence of `haskell.lib.buildStackProject`. Seems useful!

It's good to hear you figured it out.
