### ISSUE TITLE
haskell-opencv and ML

### ISSUE THREAD

**Issue by Cortlandd** [LumiGuide/haskell-opencv#67]
How should I approach implementing the Machine Learning (more specifically the Support Vector Machine sub module) module in haskell-opencv?

**Comment by basvandijk** [comment]
I haven't looked at that module yet so I have no idea.

Why don't you think about it, write a proposal describing how you want to bind that module so that we have something to review?

**Comment by Cortlandd** [comment]
Define how I'd like to bind? I figured, the same approach as any other module in the library? Follow the types. Assuming some types from ML aren't implemented in haskell-opencv?
