### ISSUE TITLE
Find Contours

### ISSUE THREAD

**Issue by Chuck-Aguilar** [LumiGuide/haskell-opencv#69]
Hi!

I'm having troubles to find the contours of an image. 

That's the definition: 
`findContours :: PrimMonad m => ContourRetrievalMode -> ContourApproximationMethod -> Mut (Mat (S '[h, w]) (S 1) (S Word8)) (PrimState m) -> m (Vector Contour)`

So, I'm using `thaw` to convert a _Mat_ in a _Mut (Mat ... )_  

But I get this error: 

`Couldn't match type ‘PrimState m’
                       with ‘CV.Mut
                               (M.Mat ('S '[h1, w1]) ('S 1) ('S Word8))
                               (PrimState (CV.Mut (M.Mat ('S '[h0, w0]) ('S 1) ('S Word8))))’
        Expected type: CV.Mut
                         (M.Mat ('S '[h0, w0]) ('S 1) ('S Word8)) (PrimState m)
          Actual type: CV.Mut
                         (M.Mat ('S '[h0, w0]) ('S 1) ('S Word8))
                         (CV.Mutable
                            (M.Mat ('S '[h1, w1]) ('S 1) ('S Word8))
                            (PrimState (CV.Mut (M.Mat ('S '[h0, w0]) ('S 1) ('S Word8)))))`

in line 29 of this [gist](https://gist.github.com/Chuck-Aguilar/f0960c91ad75a69bde1fe62e8d8c951a)

Why is it packing the whole `Mut` where PrimState should be?

**Comment by roelvandijk** [comment]
There are a number of errors in the snippet you posted.

Study the type of [`thaw`](http://lumiguide.github.io/haskell-opencv/doc/OpenCV-Core-Types-Mat.html#v:thaw). It returns a value wrapped in the `m` type. If you want to access that value you should use the `>>=` operator or `do` notation to bind it to a variable.
```haskell
example = do
    mutableValue <- thaw value
```

It is also unclear why you apply `return` to the result of [`CV.findContours`](http://lumiguide.github.io/haskell-opencv/doc/OpenCV-ImgProc-StructuralAnalysis.html#v:findContours). Again, look at the type. It returns a result in the `m` monad. The `do` block in your example is already in this monad, so you can simply bind the result to the `contours_vector` variable.

Corrected but untested example:
```haskell
findingContours :: PrimMonad m => M.Mat ('S '[h0, w0]) ('S 1) ('S Word8) -> m (Vector SA.Contour)
findingContours image = do
    imageM <- CV.thaw image
    contours_vector <- CV.findContours SA.ContourRetrievalList SA.ContourApproximationSimple imageM
    pure contours_vector
```

**Comment by Chuck-Aguilar** [comment]
yes... now it works...  :disappointed:  I was a lot of time looking what it was wrong and it was actually quite easy the answer. 

Thank you and sorry!
