### ISSUE TITLE
Uncaught exception in resize

### ISSUE THREAD

**Issue by roelvandijk** [LumiGuide/haskell-opencv#7]
```
OpenCV Error: Assertion failed (dsize.area() > 0 || (inv_scale_x > 0 && inv_scale_y > 0)) in resize, file /tmp/nix-build-opencv-3.1.0.drv-0/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp, line 3230
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/nix-build-opencv-3.1.0.drv-0/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp:3230: error: (-215) dsize.area() > 0 || (inv_scale_x > 0 && inv_scale_y > 0) in function resize
```

We probably forgot to install a Haskell exception handler for the resize function.

**Comment by roelvandijk** [comment]
Fixed by 9b4dcaedae051ce0914c1a9a887408ce667cae4d

**Comment by Cortlandd** [comment]
Did I do something bad?

**Comment by roelvandijk** [comment]
Don't worry. This was not related to the window resize function.

Under some circumstances the ORB feature detector raised an exception in C++. If you don't catch a C++ exception in your Haskell program the entire process will be killed. Installing an exception handler and wrapping the exception in Haskell solved the issue.
