### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by GildedHonour** [LumiGuide/haskell-opencv#73]
It doesn't exist at hackage. Do you have a plan to upload it there? 
Is it the only way to install it from this repository?

**Comment by tolysz** [comment]
This is a tricky question, as it all depends on the OS you have. I guess the easiest to have is some nix or debian based package manager.

**Comment by roelvandijk** [comment]
The library is now [available](https://hackage.haskell.org/package/opencv) on hackage!
