### ISSUE TITLE
Bind GrayworldWB

### ISSUE THREAD

**Issue by basvandijk** [LumiGuide/haskell-opencv#77]
@tolysz I had to [disable](https://github.com/LumiGuide/haskell-opencv/blob/master/opencv-extra/src/OpenCV/Extra/XPhoto.hs#L84) `autowbGrayworld` since `cv::xphoto::autowbGrayworld` disappeared in OpenCV-3.2.

I see that it got replaced by a `GrayworldWB` class. See http://docs.opencv.org/3.2.0/de/daa/group__xphoto.html

Care to investigate how we can get that functionality back?

**Comment by tolysz** [comment]
If there is a good way of detecting which OpenCV version do we have I made the changes to support version 3.2 only

**Comment by basvandijk** [comment]
@tolysz I guess you can use these CPP defines:

http://docs.opencv.org/3.2.0/d7/dad/version_8hpp.html

I think only targeting the latest OpenCV (3.2) is fine for now.
