### ISSUE TITLE
Consider replacing the Convert MPTC with multiple single PTC's.

### ISSUE THREAD

**Issue by basvandijk** [LumiGuide/haskell-opencv#9]
Currently when a user needs to apply a function with a polymorphic argument with a `Convert` constraint (for example the `toPoint2i` argument in [arrowedLine](http://lumiguide.github.io/haskell-opencv/doc/OpenCV-ImgProc-Drawing.html#v:arrowedLine)) and he needs to figure out what to apply it to, then he has to look at the documentation of the [Convert](http://lumiguide.github.io/haskell-opencv/doc/OpenCV-TypeLevel.html#t:Convert) multiple-parameter-type-class and look for all the instances with the desired output type. This is undesirable from a user standpoint.

It would be better to have multiple single-parameter-type-classes for each argument type. Then the user can just click on the class and immediately see what can be converted.

**Comment by basvandijk** [comment]
I did a bunch of work on this in: https://github.com/LumiGuide/haskell-opencv/commit/40d226239afbfe5139a895a1617311007a93de91

**Comment by roelvandijk** [comment]
More work done in 787c4c23fc95503cb654f84b18dcf32fc99b2ae5, 1b352ba06559c1e412c588b53bc2b64f6358d168 and 689987250a642831038ebbcc551b826e70b0e032.

We know need to figure out a nice way to convert things to the `DS` variants. This is somewhat equivalent to a `Maybe`.

Something like this:
```haskell
class ToDepthDS a where toDepthDS :: a -> DS Depth
class ToChannelsDS a where toChannelsDS :: a -> DS Int32
class ToShapeDS a where toShapeDS :: a -> DS (V.Vector (DS Int32))
```

**Comment by roelvandijk** [comment]
I think we can close this considering 5632bcd3bc36922da1d986f4721cdca11d8df5f.
