### ISSUE TITLE
How do I convert the images for use with matchTemplate?

### ISSUE THREAD

**Issue by drull95** [LumiGuide/haskell-opencv#97]
Thanks for your quick reply to my previous problem. Now my program looks like:

    workingDir = "/home/cmo/src/fps-bot/data"
    thumbnail = workingDir </> "level-thumbnail.png"
    startScreen = workingDir </> "screen-0169.png"
    
    loadImage :: FilePath -> IO (CV.Mat ('S ['D, 'D]) 'D 'D)
    loadImage path = CV.imdecode CV.ImreadColor <$> B.readFile path
    
    main = do
      w <- makeWindow "hello"
      thum <- loadImage thumbnail
      start <- loadImage startScreen
      let start' :: Mat ('S ['D, 'D]) ('S 1) ('S Word8)
          -- start' = exceptError $ coerceMat start
          start' = exceptError $ cvtColor rgb gray start
          thum' :: Mat ('S ['D, 'D]) ('S 1) ('S Word8)
          thum' = exceptError $ coerceMat thum
          m = exceptError $
                matchTemplate start' thum' MatchTemplateSqDiff MatchTemplateNormed
      imshow w m
      waitKey 5000

If I attempt to just coerce start into being the right shape the program fails because of a channel mismatch error (there are three in the image but only one is wanted for matchTemplate). cvtColor seems to work better in that I can fix the channels but I don't know how to get it to change the depth

**Comment by drull95** [comment]
My problem is that cvtColor results in

     • Couldn't match type ‘'D’ with ‘'S Word8’
      Expected type: Mat ('S '['D, 'D]) ('S 1) ('S Word8)
        Actual type: Mat ('S '['D, 'D]) ('S 1) 'D

How does one index a mat? I was thinking i could just make a new mat and initialize it using some function of the image data but I don't see how to index.

**Comment by roelvandijk** [comment]
You can use [`coerceMat`](https://hackage.haskell.org/package/opencv-0.0.1.1/docs/OpenCV-Core-Types-Mat.html#v:coerceMat) to safely change the type of a `Mat`. It computes a `Mat` inside of a `CvExcept`. This forces you to check whether the new type matches the actual matrix.

In general you now that the image you are reading from disk has `Word8` as the depth. But we can't prove that. Hence the `coerceMat` function.

**Comment by roelvandijk** [comment]
Indexing a matrix is another problem, which is not yet solved. We still need to think of a good interface. One that gives both speed and (type)safety.

Currently there are only [`unsafeRead`](http://hoogle.lumi.guide.local/file/nix/store/8mcpaxvb40kqlv4nw3015ivgzarmmpv9-opencv-HEAD/share/doc/x86_64-linux-ghc-8.0.2/opencv-0.0.0/html/OpenCV-Unsafe.html#v:unsafeRead) and [`unsafeWrite`](http://hoogle.lumi.guide.local/file/nix/store/8mcpaxvb40kqlv4nw3015ivgzarmmpv9-opencv-HEAD/share/doc/x86_64-linux-ghc-8.0.2/opencv-0.0.0/html/OpenCV-Unsafe.html#v:unsafeWrite).

`unsafeWrite` is used to implement [`matFromFunc`](http://hoogle.lumi.guide.local/file/nix/store/8mcpaxvb40kqlv4nw3015ivgzarmmpv9-opencv-HEAD/share/doc/x86_64-linux-ghc-8.0.2/opencv-0.0.0/html/OpenCV-Core-Types-Mat.html#v:matFromFunc), which is a bit easier to use, but doesn't help when you want to map over a matrix (apply a Haskell function to each pixel).

**Comment by drull95** [comment]
Strange, I could've swore that I tried coercing the mat after converting it. Ah well it works now. Thanks for your reply.
