### ISSUE TITLE
`matScalarCompare` has wrong result type

### ISSUE THREAD

**Issue by achirkin** [LumiGuide/haskell-opencv#98]
https://github.com/LumiGuide/haskell-opencv/blob/4d668c7da81eeddf2275287ec21f1c51218463f0/opencv/src/OpenCV/Core/ArrayOps.hs#L343

As per [OpenCV docs](https://docs.opencv.org/3.2.0/d2/de8/group__core__array.html#ga303cfb72acf8cbb36d884650c09a3a97), `cv::compare` operation returns `Word8` array - not the array of the same type as input; so I would suggest to put something like `IO (Mat shape channels ('S Word8))` as the output type of this function.

**Comment by roelvandijk** [comment]
You are correct. Thank you!
